fix: dynamic generic fee handler fee calcualtion
sygmaprotocol/sygma-solidity pull request #141
Opened 2023-03-01 07:56 UTC by nmlinaric

## Description
Current implementation for calculating dynamic fee for permissionless generic handler deposits won't work since it relies on `_resourceIDToTokenContractAddress` mapping existing in `PermissionlessGenericHadnerl`, this introduces a check to differentiate dynamic fee calculation for ERC20 generic deposits.

## Related Issue Or Context
Closes: #137 

## How Has This Been Tested? Testing details.
unit tests, e2e tests

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-03-01 09:11 UTC, lastperson requested changes

2023-03-01 09:11 UTC, lastperson commented on test/handlers/fee/dynamic/collectFeeGenericEVM.js
> +    const {fee} = await FeeHandlerRouterInstance.calculateFee.call(
If the fee is known to be "0.000036777" then perhaps no need to call calculateFee() ?

2023-03-01 09:11 UTC, lastperson commented on test/handlers/fee/dynamic/collectFeeGenericEVM.js
> +    );
```suggestion
    // Covered by test: deposit should revert if invalid fee (msg.value) amount supplied
```

2023-03-01 09:11 UTC, lastperson commented on test/handlers/fee/dynamic/collectFeeGenericEVM.js
> +          value: Ethers.utils.parseEther("0.5").toString(),
All test values should be valid, except for the one that is being tested.
```suggestion
          value: Ethers.utils.parseEther("0.000036777"),
```

2023-03-01 09:11 UTC, lastperson commented on test/handlers/fee/dynamic/collectFeeGenericEVM.js
> +          value: Ethers.utils.parseEther("0.5").toString(),
```suggestion
          value: Ethers.utils.parseEther("0.000036777"),
```

2023-03-01 09:11 UTC, lastperson commented on test/handlers/fee/dynamic/collectFeeGenericEVM.js
> +    const {fee} = await FeeHandlerRouterInstance.calculateFee.call(
Fee is already known, no need to call calculateFee.

2023-03-01 13:57 UTC, mpetrun5 approved these changes

2023-03-02 05:32 UTC, lastperson commented on test/handlers/fee/dynamic/collectFeeGenericEVM.js
> +          fee,
```suggestion
          value: fee,
```

2023-03-02 12:39 UTC, lastperson approved these changes

2023-03-02 12:40 UTC, merged