feat: return data from Bridge.deposit()
sygmaprotocol/sygma-solidity pull request #165
Opened 2023-04-10 11:47 UTC by viatrix

Return (depositNonce, handlerResponse) from Bridge.deposit()

## Description
Bridge will return (depositNonce, handlerResponse) from Bridge.deposit(). The returned values could be used by external adapters that interact with the Bridge.

## Related Issue Or Context
#163

Closes: #163

## How Has This Been Tested? Testing details.
Unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-04-10 14:41 UTC, lastperson requested changes

2023-04-10 14:41 UTC, lastperson commented on contracts/Bridge.sol
>          bytes memory handlerResponse = depositHandler.deposit(resourceID, sender, depositData);
```suggestion
        handlerResponse = depositHandler.deposit(resourceID, sender, depositData);
```
same or depositNonce.

2023-04-13 10:11 UTC, lastperson approved these changes

2023-04-24 09:17 UTC, nmlinaric approved these changes

2023-04-24 09:19 UTC, merged