feat: implement handler response on proposal execution
sygmaprotocol/sygma-solidity pull request #167
Opened 2023-04-13 09:43 UTC by nmlinaric

## Description
Implements `handlerReponse` in `executeProposal` function which is passed to `ProposalExecution` event.

## Related Issue Or Context
Closes: #166 

## How Has This Been Tested? Testing details.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-05-03 11:16 UTC, lastperson requested changes
1. I think we need to use abi.encode to make the data easily decodeable.
2. Wouldn't it make sense to return all the useful information from the handler if we are at it already?

2023-05-03 11:16 UTC, lastperson commented on contracts/handlers/ERC1155Handler.sol
> +        return abi.encodePacked(recipientAddress, tokenIDs);
```suggestion
        return abi.encode(recipientAddress, tokenIDs, amounts);
```

2023-05-03 11:16 UTC, lastperson commented on contracts/handlers/ERC20Handler.sol
> +        return abi.encodePacked(recipientAddress, amount);
```suggestion
        return abi.encode(tokenAddress, recipientAddress, amount);
```

2023-05-03 11:16 UTC, lastperson commented on contracts/handlers/ERC721Handler.sol
> +        return abi.encodePacked(recipientAddress, tokenID);
```suggestion
        return abi.encode(tokenAddress, recipientAddress, tokenID);
```

2023-05-03 11:16 UTC, lastperson commented on contracts/handlers/PermissionedGenericHandler.sol
> +    function executeProposal(bytes32 resourceID, bytes calldata data) external onlyBridge returns (bytes memory) {
Perhaps we should return the execution contract response?

2023-05-03 11:16 UTC, lastperson commented on contracts/handlers/PermissionlessGenericHandler.sol
> +    function executeProposal(bytes32 resourceID, bytes calldata data) external onlyBridge returns (bytes memory) {
Perhaps we should return the execution contract response?

2023-05-03 11:16 UTC, lastperson commented on contracts/handlers/XC20Handler.sol
> +        return abi.encodePacked(recipientAddress, amount);
```suggestion
        return abi.encode(tokenAddress, recipientAddress, amount);
```

2023-05-10 12:23 UTC, mpetrun5 approved these changes

2023-05-10 13:06 UTC, P1sar approved these changes

2023-05-10 13:37 UTC, lastperson approved these changes

2023-05-10 13:54 UTC, merged