fix: check successful transfer when minting XC20 tokens
sygmaprotocol/sygma-solidity pull request #186
Opened 2023-04-21 11:00 UTC by nmlinaric

## Description
Checks if transfer succeeded when transfering tokens from `XC20Safe` contract to recipient address. 
This mitigates the possibility that `transfer` failed but it looks like `mintERC20` succeeded.

## Related Issue Or Context
Closes: #168 

## How Has This Been Tested? Testing details.
unit tests

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-04-24 08:47 UTC, lastperson requested changes

2023-04-24 08:47 UTC, lastperson commented on contracts/XC20Safe.sol
> +        (bool success) = xc20.transfer(recipient, amount);
We already have _safeTransfer(), perhaps should use it instead?

2023-04-24 14:16 UTC, lastperson approved these changes

2023-04-26 09:44 UTC, MakMuftic approved these changes

2023-04-29 07:22 UTC, stevenjla approved these changes

2023-05-02 13:15 UTC, mpetrun5 approved these changes

2023-05-02 13:29 UTC, merged