fix: use custom errors to reduce gas consumption
sygmaprotocol/sygma-solidity pull request #187
Opened 2023-04-21 15:49 UTC by nmlinaric

## Description
Implement custom errors on `Bridge` and `ERC20Safe` contracts to reduce gas consumption.

## Related Issue Or Context
Closes: #179 

## How Has This Been Tested? Testing details.
unit tests

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-04-24 08:49 UTC, lastperson requested changes

2023-04-24 08:49 UTC, lastperson commented on contracts/ERC20Safe.sol
> -            require(abi.decode(returndata, (bool)), "ERC20: operation did not succeed");
Logic that verifies the returned value to be true/false must remain.
Need to have a test for this case.

2023-04-26 10:21 UTC, nmlinaric commented
NOTE: Truffle doesn't support decoding custom errors and can behave weird - this was the case with `ERC20Safe`.
Besides that we like more the consistent usage of `require` in `ERC20Safe` which can be properly tested.
Regarding gas consumption - it's more or less the same using `require` compared to `revert CustomError()`.

2023-04-26 13:39 UTC, lastperson requested changes
Tiny style fix.

2023-04-26 13:39 UTC, lastperson commented on test/helpers.js
> +    ).return
```suggestion
      (it) => it != null && it.constructor.name === "Object" && "return" in it
    ).return;
```

2023-05-02 08:16 UTC, MakMuftic approved these changes

2023-05-03 13:47 UTC, stevenjla approved these changes

2023-05-08 10:45 UTC, lastperson approved these changes

2023-05-08 11:09 UTC, merged