feat: percentage based fee handler
sygmaprotocol/sygma-solidity pull request #194
Opened 2023-08-21 08:28 UTC by nmlinaric

## Description
Introduces new fee handler that charges % from the transferred token amount.

## Related Issue Or Context
Closes: #188 

## How Has This Been Tested? Testing details.
 - unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-08-21 13:31 UTC, mpetrun5 commented on contracts/handlers/fee/PercentageERC20FeeHandler.sol
> +    @title Handles deposit fees on Substrate based on Effective rates provided by Fee oracle.
I don't think it is for substrate or by the fee oracle.

2023-08-21 13:31 UTC, mpetrun5 commented on contracts/handlers/fee/PercentageERC20FeeHandler.sol
> +    uint256 public _lowerBound; // min fee in token amount
Should this be per token @MakMuftic ?

2023-08-28 10:26 UTC, lastperson requested changes

2023-08-28 10:26 UTC, lastperson commented on test/handlers/fee/percentage/calculateFee.js
> +    assert.equal(res[0].toString(),"0");
```suggestion
    assert.equal(res[0].toString(), "0");
```

2023-08-28 10:26 UTC, lastperson commented on test/handlers/fee/percentage/calculateFee.js
> +    assert.equal(res[0].toString(),"10000");
```suggestion
    assert.equal(res[0].toString(), "10000");
```

2023-09-01 08:29 UTC, lastperson approved these changes

2023-09-01 08:39 UTC, MakMuftic approved these changes

2023-09-01 08:39 UTC, merged