Add support for different fees per dest domain to basic/percentage fee handler
sygmaprotocol/sygma-solidity pull request #206
Opened 2023-10-19 12:54 UTC by nmlinaric

## Description
This introduces a mapping for fees per destination domain. Now we don't have to deploy a new handler for every fee amount, they all can be setup in a single basic/percentage fee handler.

Also removes setting up fees in migrations since now there would be too many moving parts to do it automatically. 
In general we need to rethink about fees and how to approach to migrations.

## Related Issue Or Context
Closes: #205
Closes: #151

## How Has This Been Tested? Testing details.
existing unit and e2e tests  are updated

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-10-25 07:44 UTC, lastperson requested changes

2023-10-25 07:44 UTC, lastperson commented on contracts/handlers/fee/BasicFeeHandler.sol
> +        if (msg.value != _domainResourceIDToFee[destinationDomainID][resourceID]) revert IncorrectFeeSupplied(msg.value);
Could use a local variable to avoid multiple reads from storage.

2023-10-25 07:44 UTC, lastperson commented on contracts/handlers/fee/BasicFeeHandler.sol
> +        require(_domainResourceIDToFee[destinationDomainID][resourceID] != newFee, "Current fee is equal to new fee");
Same local var suggestion.

2023-10-26 19:29 UTC, lastperson approved these changes

2023-10-30 12:13 UTC, mpetrun5 approved these changes

2023-10-31 08:21 UTC, merged