Modified Dynamic Fee Handlers with twap oracle
sygmaprotocol/sygma-solidity pull request #236
Opened 2024-04-18 13:37 UTC by andersonlee725

Modified Dynamic Fee Handlers calculate the fee in the native coin based on the twap oracle.

## Description
Created a twap oracle using Uniswap V3.
In the Dynamic Fee Handlers, calculate the tx cost fee of the destination chain and the fee is converted to the amount in the native coin of the resource chain.
For converting, the twap oracle is used.

## Related Issue Or Context

Closes: #<issue>

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-04-19 14:18 UTC, viatrix requested changes

2024-04-19 15:29 UTC, viatrix approved these changes

2024-04-22 15:46 UTC, viatrix approved these changes

2024-04-23 07:28 UTC, lastperson requested changes
Need to account for possibility where there is no destination domain wrap pool available. In such case it should be possible to manually set the price rate.

2024-04-23 07:28 UTC, lastperson commented on contracts/handlers/fee/V2/DynamicFeeHandlerV2.sol
> +        @notice Sets the fee oracle address for signature verification.
Outdated notice.

2024-04-24 13:33 UTC, andersonlee725 commented on contracts/handlers/fee/V2/TwapOracle.sol
> +    uint24[] internal _knownFeeTiers;
Will remove it.

2024-04-24 13:35 UTC, andersonlee725 commented on contracts/utils/TickMath.sol
> +/// @title Math library for computing sqrt prices from ticks and vice versa
The lib from the default dependency uses solidity >=0.5.0 <0.8.0.
So I had to copy from another branch of openzeppelin.

2024-04-24 13:36 UTC, andersonlee725 commented on contracts/handlers/fee/V2/TwapOracle.sol
> +    mapping(address => mapping(address => address)) public pools;
Okay, will make it to single mapping and add the time window into the mapping as well.

2024-04-26 19:06 UTC, viatrix approved these changes

2024-04-29 06:57 UTC, lastperson approved these changes

2024-05-02 08:42 UTC, nmlinaric approved these changes

2024-05-02 08:42 UTC, merged