feat: add native token handler adapter
sygmaprotocol/sygma-solidity pull request #253
Opened 2024-06-20 15:00 UTC by nmlinaric

## Description
Adds adapter for native token trasnfers via GMP.

## Related Issue Or Context

Closes: #231 

## How Has This Been Tested? Testing details.
unit and e2e tests 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-06-20 15:01 UTC, nmlinaric commented
I still need to add tests for deposit logic and some edge cases - I'll do it next week

2024-06-24 11:11 UTC, lastperson requested changes
If native currencies are of the same value between the origin and destination, then perhaps we should have a single adapter implementation deployed on both chains to facilitate movement in both directions?

2024-06-24 11:11 UTC, lastperson commented on contracts/adapters/nativeTokens/DestinationAdapter.sol
> +        (recipient, amount) = abi.decode(data, (address, uint256));
```suggestion
    function transferFunds(address originAdapter, address payable recipient, uint256 amount) external {
        if(_originAdapter != originAdapter) revert InvalidOriginAdapter(originAdapter);
        if(msg.sender != _gmpAddress) revert InvalidHandler(msg.sender);
```

2024-06-24 11:11 UTC, lastperson commented on contracts/adapters/nativeTokens/DestinationAdapter.sol
> +    address _gmpAddress;
```suggestion
    address immutable _gmpAddress;
```

2024-06-25 09:07 UTC, lastperson requested changes

2024-06-25 09:07 UTC, lastperson commented on contracts/adapters/interfaces/IDepositAdapterTarget.sol
> +    function transferFunds(address originAdapter, bytes calldata depositData) external;
```suggestion
    function transferFunds(address originAdapter, address payable recipient, uint256 amount) external;
```

2024-06-25 09:07 UTC, lastperson commented on contracts/adapters/nativeTokens/DestinationAdapter.sol
> +contract DestinationAdapter is AccessControl {
```suggestion
contract DestinationAdapter is IDepositAdapterTarget, AccessControl {
```
To make sure the transferFunds is compatible.

2024-06-25 09:07 UTC, lastperson commented on contracts/adapters/nativeTokens/OriginAdapter.sol
> +        _feeHandler = feeHandler;
Any reason why the fee handler is set separately instead of being fetched from the bridge when the fee calculation is required?

2024-07-10 12:19 UTC, lastperson approved these changes

2024-07-15 14:56 UTC, mpetrun5 reviewed
The implementation is OK, though I would consider adapter implementations be part of another repo with them. 
`sygma-solidity` IMO should only be for core solidity stuff.

2024-10-15 15:32 UTC, nmlinaric commented
Closing this as for the time being it will not be used in production

2024-10-15 15:32 UTC, closed without merging