chore: erc20 contract call tests
sygmaprotocol/sygma-solidity pull request #274
Opened 2024-09-17 10:45 UTC by nmlinaric

## Description
unit tests for new erc20 and native token handles optional contract call

2024-09-17 12:17 UTC, mpetrun5 approved these changes
I guess it looks good. 
Just a small nitpick.

2024-09-17 12:17 UTC, mpetrun5 commented on test/handlers/erc20/optionalContracCall/executeProposal.js
> +    // eslint-disable-next-line max-len
I'm doubtfull this is needed.

2024-09-17 12:17 UTC, mpetrun5 commented on test/handlers/erc20/optionalContracCall/executeProposal.js
> +    // eslint-disable-next-line max-len
There is a couple of them which are unnecessary.

2024-09-18 09:11 UTC, lastperson requested changes
This is good.
We also need tests for the default message receiver.

2024-09-19 18:23 UTC, lastperson approved these changes

2024-09-19 18:29 UTC, merged